version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/riskbuster
      - public-data:/riskbuster/public
      - tmp-data:/riskbuster/tmp
      - log-data:/riskbuster/log
    networks:
      - riskbuster-network

  web:
    build:
      context: ./nginx_docker_prod
    volumes:
      - public-data:/riskbuster/public
      - tmp-data:/riskbuster/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - riskbuster-network
volumes:
  public-data:

  tmp-data:
  log-data:
  db-data:

networks:
  riskbuster-network:
    external: true
