version: '3'
services:
  app:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/riskbuster
      - public-data:/riskbuster/public
      - tmp-data:/riskbuster/tmp
      - log-data:/riskbuster/log
    networks:
      - riskbuster-network
    depends_on:
       - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: riskbuster_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - riskbuster-network

  web:
    build:
      context: ./nginx_docker_dev
    volumes:
      - public-data:/riskbuster/public
      - tmp-data:/riskbuster/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - riskbuster-network
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:

networks:
  riskbuster-network:
    external: true
