version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
jobs:
  rspec:
    working_directory: ~/riskbuster
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Setup environment variable
          command: |
            echo "export COMPOSE_FILE=docker-compose.ci.yml" >> $BASH_ENV
      - run:
          name: Start containers and verify it is working
          command: |
            set -x
            docker network create riskbuster-network
            docker-compose up -d
            docker exec riskbuster_app_1 curl -4 --retry 10 --retry-delay 3 --retry-connrefused http://localhost:80
      - run:
          name: db migrate
          command: docker-compose exec app bundle exec rails db:migrate
      - run:
          name: Database setup
          command: docker-compose exec app bundle exec rails db:schema:load --trace
      - run:
          name: Run rspec
          command: docker-compose exec app rspec

  rubocop:
    working_directory: ~/riskbuster
    docker:
      - image: circleci/ruby:3.0.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run: bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 11:2e:87:19:07:a1:d7:08:07:16:ca:a0:5c:1f:88:e2
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/riskbuster/deploy-me.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - rspec
      - rubocop
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
